#!/bin/zsh
##? mand - Read man page with Dash.app.
local -a o_docset=(manpages)
zmodload zsh/zutil
zparseopts -D -F -K -- \
  {d,-docset}:=o_docset ||
  return 1

dashcmd="dash://${o_docset[-1]}%3A$1"
open -a Dash.app $dashcmd 2> /dev/null
if test $? -ne 0; then
  echo >&2 "$0: Dash is not installed"
  return 2
fi
