#!/bin/zsh
# function antidote {
0=${(%):-%x}
if (( ! $+functions[antidote-main] )); then
  fpath+=(${HOMEBREW_PREFIX:=/opt/homebrew}/opt/antidote/share/antidote/functions)
  autoload -Uz $fpath[-1]/*(N.:t)
  __antidote_core
fi
antidote-main "$@"
# }
