#!/usr/bin/env zsh

##? Lazy-load wrapper for antidote.

if [[ ! -f ${ZDOTDIR:-~}/.antidote/antidote.zsh ]]; then
  echo >&2 "Antidote not found."
  return 1
fi

source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote $@
