#!/bin/zsh
##? autoload-dir - autoload all function files in specified directory.

local dir
local fnfile
for dir in $@; do
  [[ -d "$dir" ]] || continue
  fpath=($dir $fpath)
  for fnfile in "$dir"/*(.N); do
    [[ $fnfile:t != '_'* ]] || continue
    autoload -Uz $fnfile
  done
done
