#!/usr/bin/env zsh
##? Copy an Azure PostgreSQL access token to the clipboard.
local token
token=$(az account get-access-token \
  --resource https://ossrdbms-aad.database.windows.net \
  --query accessToken \
  --output tsv) || return 1

print -r -- "$token"
print -rn -- "$token" | pbcopy
