#!/usr/bin/env zsh
##? Change to the project root.
local root
root=$(git rev-parse --show-toplevel 2>/dev/null)
if [[ -z $root ]]; then
  print -ru2 "cdpr: not in a Git repository: $PWD"
  return 1
fi

cd -- "$root"
