#!/usr/bin/env zsh

##? fnhelp
##?    use '##?' comments in function files as help docs.
##?
##? usage:
##?   fnhelp <func>

if [[ ! -f $ZDOTDIR/functions/$1 ]]; then
  echo >&2 "Function not found '$1'."
  return 1
fi

command grep "^##?" "$ZDOTDIR/functions/$1" | cut -c 5-
