#!/usr/bin/env zsh

function _g_clone() {
  if [[ $# -lt 2 ]]; then
    command git "$@"
    return $?
  fi
  local repo="${@[-1]}"
  if [[ $repo != git://* &&
        $repo != https://* &&
        $repo != http://* &&
        $repo != ssh://* &&
        $repo != git@*:*/* ]];
  then
    if [[ $repo == */* ]]; then
      repo="git@github.com:${repo%.git}.git"
    else
      repo="git@github.com:mattmc3/${repo}.git"
    fi
    command git ${@[@]:1:-1} $repo
  else
    command git $@
  fi
}

main() {
  # No arguments: `git status`
  # With arguments: acts like `git`
  if [[ $# -eq 0 ]]; then
    command git status -sb
  elif (( $+functions[_g_${1}] )); then
    _g_${1} "$@"
    return $?
  else
    command git $@
  fi
}
main $@
