#!/bin/zsh
##? plugin-updatecheck - check whether plugins have been updated recently
#function plugin-updatecheck {
emulate -L zsh; setopt local_options extended_glob
ZPLUGINDIR=${ZPLUGINDIR:-${ZDOTDIR:-$HOME/.config/zsh}/plugins}
local lastupdated="$ZPLUGINDIR/.lastupdated"
if [[ ! -f "$lastupdated" ]]; then
  mkdir -p "${lastupdated:h}"
  date '+%Y-%m-%d %H:%M:%S' >"$lastupdated"
fi

# Test by changing date on .lastupdated file.
# touch -a -m -t 200101010909.09 "$ZPLUGINDIR/.lastupdated"
local -a oldfiles=($lastupdated(Nmw+1))
(( $#oldfiles )) && plugin-update
#}
