#!/bin/zsh

##? substenv - substitute value in shell strings with environment variable
# function substenv {

# The opposite of envsubst.
if (( $# == 0 )); then
  substenv ZDOTDIR | substenv HOME
else
  local sedexp="s|${(P)1}|\$$1|g"
  shift
  sed "$sedexp" "$@"
fi

# }
