#!/bin/zsh
##? up - go up any number of directories
##?
##? usage:
##?   up [<num>]

# function up {
if [[ "$#" -ne 1 ]]
then
  cd ..
elif ! [[ $1 =~ '^[0-9]+$' ]]
then
  echo >&2 "up: expecting a numeric parameter" && return 1
else
  local i balloons=""
  for i in {1..$1}
  do
    balloons="../$balloons"
  done
  cd $balloons
fi
# }
