#!/bin/zsh
0=${(%):-%x}

if ! (( $+commands[starship] )); then
  if (( $+commands[brew] )); then
    command brew install starship
  else
    echo >&2 "Starship prompt not installed. See https://starship.rs"
    return 1
  fi
fi

# Set the config
local prompt_config
zstyle -s ':zsh:prompt:starship' config prompt_config
if [[ -n "$prompt_config" ]]; then
  prompt_config=$ZDOTDIR/themes/${prompt_config}.toml
  [[ -f $prompt_config ]] && export STARSHIP_CONFIG=$prompt_config
fi

#eval "$(starship init zsh)"
source <(starship init zsh --print-full-init)

# vim: ft=zsh sw=2 ts=2 et
