#!/bin/zsh

##? funchelp - use '##?' comments in function files as help docs
##?
##? usage: funchelp <func>

emulate -L zsh
setopt local_options extended_glob rc_expand_param

local funcs=(${fpath}/$1(N))
if (( $#funcs )); then
  print "# Defined in $funcs[1]"
  command grep "^##?" "$funcs[1]" | cut -c 5-
else
  echo >&2 "funchelp: function not found '$1'."
  return 1
fi
