#!/bin/zsh

##? zsh_prompt - set zsh prompt
#function zsh_prompt {
  # https://unix.stackexchange.com/questions/685666/zsh-how-do-i-remove-block-prefixes-when-writing-multi-line-statements-in-intera
  # use 2 space indent for each new level
  PS2='${${${(%):-%_}//[^ ]}// /  }    '

  # Options
  setopt PROMPT_SUBST  # expand parameters in prompt variables
  autoload -Uz promptinit && promptinit

  # Set the prompt theme
  (( ! $# )) || prompt $@
#}
