#!/bin/zsh

##? zsh_funcdir - use a Fish-like functions directory for lazy-loaded functions.
#function zsh_funcdir {
  local fn fndir funcdir=$ZDOTDIR/functions
  [[ -d $funcdir ]] || return 1
  for fndir in $funcdir(/FN) $funcdir/*(/FN); do
    fpath=($fndir $fpath)
  done
  for fn in $funcdir/*(.N) $funcdir/*/*(.N); do
    [[ $fn:t != '_'* ]] || continue
    autoload -Uz $fn:t
  done
#}
