#!/bin/zsh
#
# zshinit
#

local prompt_theme
zstyle -s ':zsh:prompt' theme prompt_theme

# initialize core zsh
autoload -Uz zsh_funcdir && zsh_funcdir
zsh_antidote
zsh_prompt $prompt_theme
zsh_options
zsh_history
zsh_utility
zsh_color
zsh_confd
zsh_compstyle
zsh_completion

# Load aliases.
[[ -f $ZDOTDIR/.zaliases ]] && source $ZDOTDIR/.zaliases

# Local settings/overrides.
[[ -f $ZDOTDIR/.zshrc_local ]] && $ZDOTDIR/.zshrc_local
