#!/bin/zsh

##? zsh_prompt - set zsh prompt
#function zsh_prompt {
  # https://unix.stackexchange.com/questions/685666/zsh-how-do-i-remove-block-prefixes-when-writing-multi-line-statements-in-intera
  # use 2 space indent for each new level
  PS2='${${${(%):-%_}//[^ ]}// /  }    '

  # Options
  setopt PROMPT_SUBST  # expand parameters in prompt variables
  autoload -Uz promptinit && promptinit

  # Set the prompt theme
  if (( $# )); then
    prompt $@

    # Set the prompt config
    local prompt_config
    zstyle -s ':zsh:prompt' config prompt_config
    if [[ "$1" == "powerlevel10k" ]] && [[ -n "$prompt_config" ]]; then
      prompt_config=$ZDOTDIR/themes/${prompt_config}.p10k.zsh

      # To customize prompt, run `p10k configure` or edit ${ZDOTDIR:-~}/.p10k.zsh.
      [[ -f $prompt_config ]] || prompt_config=${ZDOTDIR:-~}/.p10k.zsh
      source $prompt_config
    fi
  fi
#}
