#!/bin/zsh

##? zsh_options - set better zsh options than the defaults
#function zsh_options {
  local zopts=(
    # 16.2.1 Changing Directories
    auto_cd                 # if a command isn't valid, but is a directory, cd to that dir.
    auto_pushd              # make cd push the old directory onto the dirstack.
    cdable_vars             # change directory to a path stored in a variable.
    pushd_ignore_dups       # don’t push multiple copies of the same directory onto the dirstack.
    pushd_minus             # exchanges meanings of +/- when navigating the dirstack.
    pushd_silent            # do not print the directory stack after pushd or popd.
    pushd_to_home           # push to home directory when no argument is given.

    # 16.2.3 Expansion and Globbing
    extended_glob           # Use extended globbing syntax.
    glob_dots               # Don't hide dotfiles from glob patterns.

    # 16.2.6 Input/Output
    interactive_comments    # Enable comments in interactive shell.
    rc_quotes               # Allow 'Hitchhiker''s Guide' instead of 'Hitchhiker'\''s Guide'.
    NO_clobber              # Don't overwrite files with >. Use >| to bypass.
    NO_mail_warning         # Don't print a warning if a mail file was accessed.
    NO_rm_star_silent       # Ask for confirmation for `rm *' or `rm path/*'

    # 16.2.7 Job Control
    auto_resume             # Attempt to resume existing job before creating a new process.
    long_list_jobs          # List jobs in the long format by default.
    notify                  # Report status of background jobs immediately.
    NO_bg_nice              # Don't run all background jobs at a lower priority.
    NO_check_jobs           # Don't report on jobs when shell exit.
    NO_hup                  # Don't kill jobs on shell exit.

    # 16.2.9 Scripts and Functions
    multios                 # Write to multiple descriptors.

    # 16.2.12 Zle
    combining_chars         # Combine 0-len chars with base chars (eg: accents).
    NO_beep                 # Be quiet.
  )
  setopt $zopts
#}
