#!/bin/zsh

# Be sure OMZ's requirements are set up.
[[ -n "$ZSH" ]] || ZSH="$(antidote path ohmyzsh/ohmyzsh)"

# Use the 'getantidote/use-omz' plugin to lazy-load whatever you need from OMZ!
# If you don't, you will need to load all the $ZSH/lib prerequisites yourself, and
# may need to uncomment this line:
# source $ZSH/lib/*.zsh

# Now, load whatever OMZ theme.
[[ -n "$ZSH_THEME" ]] || ZSH_THEME="${1:-robbyrussell}"
source $ZSH/themes/${ZSH_THEME}.zsh-theme
