add_newline = false

# Two-line left prompt, nothing on the right.
format = """
$directory\
$git_branch\
$git_status\
$status\
$cmd_duration
$python\
$character\
"""

# Timeout for commands executed by starship (in milliseconds)
command_timeout = 2000

# Set the palette.
palette = "blue_matrix"

[profiles]
transient = '$time[❯](bold cyan) '
transient_success = '$time[❯](bold green) '
transient_error = '$status'

[palettes.wombat]
black = '#000000'
red = '#ff615a'
green = '#b1e969'
yellow = '#ebd99c'
blue = '#5da9f6'
purple = '#e86aff'
cyan = '#82fff7'
white = '#dedacf'

[palettes.blue_matrix]
black = '#101116'
red = '#ff5680'
green = '#00ff9c'
yellow = '#fffc58'
blue = '#00b0ff'
purple = '#d57bff'
cyan = '#76c1ff'
white = '#c7c7c7'
brblack = '#686868'
brred = '#ff6e67'
brgreen = '#5ffa68'
bryellow = '#fffc67'
brblue = '#6871ff'
brpurple = '#d682ec'
brcyan = '#60fdff'
brwhite = '#ffffff'
background = '#101116'
foreground = '#00a2ff'
cursor-color = '#76ff9f'
cursor-text = '#a6a6a6'
selection-background = '#c1deff'
selection-foreground = '#000000'

[character]
success_symbol = "[❯](purple)[❯](cyan)"
error_symbol = "[❯](yellow)[❯](red)"
vicmd_symbol = "[❮](purple)[❮](cyan)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = 'white'

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
style = "blue"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = ' [$branch]($style)'
style = 'green'

[git_status]
format = '([*$conflicted$deleted$renamed$modified$typechanged$staged$untracked](yellow))([\[$ahead_behind$stashed\]]($style))'
style = "cyan"
stashed = "≡"
conflicted = "​"
deleted = "​"
renamed = "​"
modified = "​"
typechanged = "​"
staged = "​"
untracked = "​"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
format = ' [$duration]($style)'

[shell]
fish_indicator = '🐟'
powershell_indicator = '_'
pwsh_indicator = '_'
zsh_indicator = '󠀥%'
style = 'cyan bold'
disabled = false

[status]
disabled = false
pipestatus = true
format = ' [($symbol$int)]($style)'
symbol = '✘'
pipestatus_format = ' \[$pipestatus\]($style)'

[time]
disabled = false
format = '[$time]($style) '
time_format = '%H:%M:%S'
style = 'brblack'
