#!/bin/zsh
##? Open a Jupyter notebook.

if ! venv -p juno 2>/dev/null; then
  venv juno
  pip install --upgrade pip
  pip install jupyterlab
  pip install pandas
fi

local jupyter_prj=$HOME/Projects/mattmc3/jupyter
if [[ ! -d $jupyter_prj ]]; then
  git clone git@github.com:mattmc3/jupyter $jupyter_prj
fi

jupyter lab ${1:-$jupyter_prj}
